// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: multipaxosrpc.proto

package comm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MultiPaxosRPCClient is the client API for MultiPaxosRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MultiPaxosRPCClient interface {
	Accept(ctx context.Context, in *AcceptRequest, opts ...grpc.CallOption) (*AcceptResponse, error)
	Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
}

type multiPaxosRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewMultiPaxosRPCClient(cc grpc.ClientConnInterface) MultiPaxosRPCClient {
	return &multiPaxosRPCClient{cc}
}

func (c *multiPaxosRPCClient) Accept(ctx context.Context, in *AcceptRequest, opts ...grpc.CallOption) (*AcceptResponse, error) {
	out := new(AcceptResponse)
	err := c.cc.Invoke(ctx, "/multipaxosrpc.MultiPaxosRPC/Accept", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiPaxosRPCClient) Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error) {
	out := new(PrepareResponse)
	err := c.cc.Invoke(ctx, "/multipaxosrpc.MultiPaxosRPC/Prepare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiPaxosRPCClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, "/multipaxosrpc.MultiPaxosRPC/Commit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MultiPaxosRPCServer is the server API for MultiPaxosRPC service.
// All implementations must embed UnimplementedMultiPaxosRPCServer
// for forward compatibility
type MultiPaxosRPCServer interface {
	Accept(context.Context, *AcceptRequest) (*AcceptResponse, error)
	Prepare(context.Context, *PrepareRequest) (*PrepareResponse, error)
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	mustEmbedUnimplementedMultiPaxosRPCServer()
}

// UnimplementedMultiPaxosRPCServer must be embedded to have forward compatible implementations.
type UnimplementedMultiPaxosRPCServer struct {
}

func (UnimplementedMultiPaxosRPCServer) Accept(context.Context, *AcceptRequest) (*AcceptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Accept not implemented")
}
func (UnimplementedMultiPaxosRPCServer) Prepare(context.Context, *PrepareRequest) (*PrepareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedMultiPaxosRPCServer) Commit(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedMultiPaxosRPCServer) mustEmbedUnimplementedMultiPaxosRPCServer() {}

// UnsafeMultiPaxosRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MultiPaxosRPCServer will
// result in compilation errors.
type UnsafeMultiPaxosRPCServer interface {
	mustEmbedUnimplementedMultiPaxosRPCServer()
}

func RegisterMultiPaxosRPCServer(s grpc.ServiceRegistrar, srv MultiPaxosRPCServer) {
	s.RegisterService(&MultiPaxosRPC_ServiceDesc, srv)
}

func _MultiPaxosRPC_Accept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiPaxosRPCServer).Accept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/multipaxosrpc.MultiPaxosRPC/Accept",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiPaxosRPCServer).Accept(ctx, req.(*AcceptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiPaxosRPC_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiPaxosRPCServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/multipaxosrpc.MultiPaxosRPC/Prepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiPaxosRPCServer).Prepare(ctx, req.(*PrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiPaxosRPC_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiPaxosRPCServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/multipaxosrpc.MultiPaxosRPC/Commit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiPaxosRPCServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MultiPaxosRPC_ServiceDesc is the grpc.ServiceDesc for MultiPaxosRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MultiPaxosRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "multipaxosrpc.MultiPaxosRPC",
	HandlerType: (*MultiPaxosRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Accept",
			Handler:    _MultiPaxosRPC_Accept_Handler,
		},
		{
			MethodName: "Prepare",
			Handler:    _MultiPaxosRPC_Prepare_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _MultiPaxosRPC_Commit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "multipaxosrpc.proto",
}
