// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.12.4
// source: multipaxosrpc.proto

package comm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseType int32

const (
	ResponseType_OK     ResponseType = 0
	ResponseType_REJECT ResponseType = 1
)

// Enum value maps for ResponseType.
var (
	ResponseType_name = map[int32]string{
		0: "OK",
		1: "REJECT",
	}
	ResponseType_value = map[string]int32{
		"OK":     0,
		"REJECT": 1,
	}
)

func (x ResponseType) Enum() *ResponseType {
	p := new(ResponseType)
	*p = x
	return p
}

func (x ResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_multipaxosrpc_proto_enumTypes[0].Descriptor()
}

func (ResponseType) Type() protoreflect.EnumType {
	return &file_multipaxosrpc_proto_enumTypes[0]
}

func (x ResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseType.Descriptor instead.
func (ResponseType) EnumDescriptor() ([]byte, []int) {
	return file_multipaxosrpc_proto_rawDescGZIP(), []int{0}
}

type CommandType int32

const (
	CommandType_GET CommandType = 0
	CommandType_PUT CommandType = 1
	CommandType_DEL CommandType = 2
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "GET",
		1: "PUT",
		2: "DEL",
	}
	CommandType_value = map[string]int32{
		"GET": 0,
		"PUT": 1,
		"DEL": 2,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_multipaxosrpc_proto_enumTypes[1].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_multipaxosrpc_proto_enumTypes[1]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_multipaxosrpc_proto_rawDescGZIP(), []int{1}
}

type InstanceState int32

const (
	InstanceState_INPROGRESS InstanceState = 0
	InstanceState_COMMITTED  InstanceState = 1
	InstanceState_EXECUTED   InstanceState = 2
)

// Enum value maps for InstanceState.
var (
	InstanceState_name = map[int32]string{
		0: "INPROGRESS",
		1: "COMMITTED",
		2: "EXECUTED",
	}
	InstanceState_value = map[string]int32{
		"INPROGRESS": 0,
		"COMMITTED":  1,
		"EXECUTED":   2,
	}
)

func (x InstanceState) Enum() *InstanceState {
	p := new(InstanceState)
	*p = x
	return p
}

func (x InstanceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstanceState) Descriptor() protoreflect.EnumDescriptor {
	return file_multipaxosrpc_proto_enumTypes[2].Descriptor()
}

func (InstanceState) Type() protoreflect.EnumType {
	return &file_multipaxosrpc_proto_enumTypes[2]
}

func (x InstanceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstanceState.Descriptor instead.
func (InstanceState) EnumDescriptor() ([]byte, []int) {
	return file_multipaxosrpc_proto_rawDescGZIP(), []int{2}
}

type AcceptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Sender        int64                  `protobuf:"varint,2,opt,name=sender,proto3" json:"sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRequest) Reset() {
	*x = AcceptRequest{}
	mi := &file_multipaxosrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRequest) ProtoMessage() {}

func (x *AcceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxosrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRequest.ProtoReflect.Descriptor instead.
func (*AcceptRequest) Descriptor() ([]byte, []int) {
	return file_multipaxosrpc_proto_rawDescGZIP(), []int{0}
}

func (x *AcceptRequest) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *AcceptRequest) GetSender() int64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

type AcceptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ResponseType           `protobuf:"varint,1,opt,name=type,proto3,enum=multipaxosrpc.ResponseType" json:"type,omitempty"`
	Ballot        int64                  `protobuf:"varint,2,opt,name=ballot,proto3" json:"ballot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptResponse) Reset() {
	*x = AcceptResponse{}
	mi := &file_multipaxosrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptResponse) ProtoMessage() {}

func (x *AcceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxosrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptResponse.ProtoReflect.Descriptor instead.
func (*AcceptResponse) Descriptor() ([]byte, []int) {
	return file_multipaxosrpc_proto_rawDescGZIP(), []int{1}
}

func (x *AcceptResponse) GetType() ResponseType {
	if x != nil {
		return x.Type
	}
	return ResponseType_OK
}

func (x *AcceptResponse) GetBallot() int64 {
	if x != nil {
		return x.Ballot
	}
	return 0
}

type PrepareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        int64                  `protobuf:"varint,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Sender        int64                  `protobuf:"varint,2,opt,name=sender,proto3" json:"sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareRequest) Reset() {
	*x = PrepareRequest{}
	mi := &file_multipaxosrpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRequest) ProtoMessage() {}

func (x *PrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxosrpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRequest.ProtoReflect.Descriptor instead.
func (*PrepareRequest) Descriptor() ([]byte, []int) {
	return file_multipaxosrpc_proto_rawDescGZIP(), []int{2}
}

func (x *PrepareRequest) GetBallot() int64 {
	if x != nil {
		return x.Ballot
	}
	return 0
}

func (x *PrepareRequest) GetSender() int64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

type PrepareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ResponseType           `protobuf:"varint,1,opt,name=type,proto3,enum=multipaxosrpc.ResponseType" json:"type,omitempty"`
	Ballot        int64                  `protobuf:"varint,2,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Logs          []*Instance            `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareResponse) Reset() {
	*x = PrepareResponse{}
	mi := &file_multipaxosrpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareResponse) ProtoMessage() {}

func (x *PrepareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxosrpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareResponse.ProtoReflect.Descriptor instead.
func (*PrepareResponse) Descriptor() ([]byte, []int) {
	return file_multipaxosrpc_proto_rawDescGZIP(), []int{3}
}

func (x *PrepareResponse) GetType() ResponseType {
	if x != nil {
		return x.Type
	}
	return ResponseType_OK
}

func (x *PrepareResponse) GetBallot() int64 {
	if x != nil {
		return x.Ballot
	}
	return 0
}

func (x *PrepareResponse) GetLogs() []*Instance {
	if x != nil {
		return x.Logs
	}
	return nil
}

type CommitRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Ballot             int64                  `protobuf:"varint,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	LastExecuted       int64                  `protobuf:"varint,2,opt,name=last_executed,json=lastExecuted,proto3" json:"last_executed,omitempty"`
	GlobalLastExecuted int64                  `protobuf:"varint,3,opt,name=global_last_executed,json=globalLastExecuted,proto3" json:"global_last_executed,omitempty"`
	Sender             int64                  `protobuf:"varint,4,opt,name=sender,proto3" json:"sender,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_multipaxosrpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxosrpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_multipaxosrpc_proto_rawDescGZIP(), []int{4}
}

func (x *CommitRequest) GetBallot() int64 {
	if x != nil {
		return x.Ballot
	}
	return 0
}

func (x *CommitRequest) GetLastExecuted() int64 {
	if x != nil {
		return x.LastExecuted
	}
	return 0
}

func (x *CommitRequest) GetGlobalLastExecuted() int64 {
	if x != nil {
		return x.GlobalLastExecuted
	}
	return 0
}

func (x *CommitRequest) GetSender() int64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ResponseType           `protobuf:"varint,1,opt,name=type,proto3,enum=multipaxosrpc.ResponseType" json:"type,omitempty"`
	Ballot        int64                  `protobuf:"varint,2,opt,name=ballot,proto3" json:"ballot,omitempty"`
	LastExecuted  int64                  `protobuf:"varint,3,opt,name=last_executed,json=lastExecuted,proto3" json:"last_executed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_multipaxosrpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxosrpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_multipaxosrpc_proto_rawDescGZIP(), []int{5}
}

func (x *CommitResponse) GetType() ResponseType {
	if x != nil {
		return x.Type
	}
	return ResponseType_OK
}

func (x *CommitResponse) GetBallot() int64 {
	if x != nil {
		return x.Ballot
	}
	return 0
}

func (x *CommitResponse) GetLastExecuted() int64 {
	if x != nil {
		return x.LastExecuted
	}
	return 0
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CommandType            `protobuf:"varint,1,opt,name=type,proto3,enum=multipaxosrpc.CommandType" json:"type,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_multipaxosrpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxosrpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_multipaxosrpc_proto_rawDescGZIP(), []int{6}
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_GET
}

func (x *Command) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Command) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Instance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        int64                  `protobuf:"varint,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Index         int64                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	ClientId      int64                  `protobuf:"varint,3,opt,name=clientId,proto3" json:"clientId,omitempty"`
	State         InstanceState          `protobuf:"varint,4,opt,name=state,proto3,enum=multipaxosrpc.InstanceState" json:"state,omitempty"`
	Command       *Command               `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_multipaxosrpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxosrpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_multipaxosrpc_proto_rawDescGZIP(), []int{7}
}

func (x *Instance) GetBallot() int64 {
	if x != nil {
		return x.Ballot
	}
	return 0
}

func (x *Instance) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Instance) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Instance) GetState() InstanceState {
	if x != nil {
		return x.State
	}
	return InstanceState_INPROGRESS
}

func (x *Instance) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

var File_multipaxosrpc_proto protoreflect.FileDescriptor

const file_multipaxosrpc_proto_rawDesc = "" +
	"\n" +
	"\x13multipaxosrpc.proto\x12\rmultipaxosrpc\"\\\n" +
	"\rAcceptRequest\x123\n" +
	"\binstance\x18\x01 \x01(\v2\x17.multipaxosrpc.InstanceR\binstance\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\x03R\x06sender\"Y\n" +
	"\x0eAcceptResponse\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.multipaxosrpc.ResponseTypeR\x04type\x12\x16\n" +
	"\x06ballot\x18\x02 \x01(\x03R\x06ballot\"@\n" +
	"\x0ePrepareRequest\x12\x16\n" +
	"\x06ballot\x18\x01 \x01(\x03R\x06ballot\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\x03R\x06sender\"\x87\x01\n" +
	"\x0fPrepareResponse\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.multipaxosrpc.ResponseTypeR\x04type\x12\x16\n" +
	"\x06ballot\x18\x02 \x01(\x03R\x06ballot\x12+\n" +
	"\x04logs\x18\x03 \x03(\v2\x17.multipaxosrpc.InstanceR\x04logs\"\x96\x01\n" +
	"\rCommitRequest\x12\x16\n" +
	"\x06ballot\x18\x01 \x01(\x03R\x06ballot\x12#\n" +
	"\rlast_executed\x18\x02 \x01(\x03R\flastExecuted\x120\n" +
	"\x14global_last_executed\x18\x03 \x01(\x03R\x12globalLastExecuted\x12\x16\n" +
	"\x06sender\x18\x04 \x01(\x03R\x06sender\"~\n" +
	"\x0eCommitResponse\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.multipaxosrpc.ResponseTypeR\x04type\x12\x16\n" +
	"\x06ballot\x18\x02 \x01(\x03R\x06ballot\x12#\n" +
	"\rlast_executed\x18\x03 \x01(\x03R\flastExecuted\"a\n" +
	"\aCommand\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.multipaxosrpc.CommandTypeR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\xba\x01\n" +
	"\bInstance\x12\x16\n" +
	"\x06ballot\x18\x01 \x01(\x03R\x06ballot\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x03R\x05index\x12\x1a\n" +
	"\bclientId\x18\x03 \x01(\x03R\bclientId\x122\n" +
	"\x05state\x18\x04 \x01(\x0e2\x1c.multipaxosrpc.InstanceStateR\x05state\x120\n" +
	"\acommand\x18\x05 \x01(\v2\x16.multipaxosrpc.CommandR\acommand*\"\n" +
	"\fResponseType\x12\x06\n" +
	"\x02OK\x10\x00\x12\n" +
	"\n" +
	"\x06REJECT\x10\x01*(\n" +
	"\vCommandType\x12\a\n" +
	"\x03GET\x10\x00\x12\a\n" +
	"\x03PUT\x10\x01\x12\a\n" +
	"\x03DEL\x10\x02*<\n" +
	"\rInstanceState\x12\x0e\n" +
	"\n" +
	"INPROGRESS\x10\x00\x12\r\n" +
	"\tCOMMITTED\x10\x01\x12\f\n" +
	"\bEXECUTED\x10\x022\xed\x01\n" +
	"\rMultiPaxosRPC\x12G\n" +
	"\x06Accept\x12\x1c.multipaxosrpc.AcceptRequest\x1a\x1d.multipaxosrpc.AcceptResponse\"\x00\x12J\n" +
	"\aPrepare\x12\x1d.multipaxosrpc.PrepareRequest\x1a\x1e.multipaxosrpc.PrepareResponse\"\x00\x12G\n" +
	"\x06Commit\x12\x1c.multipaxosrpc.CommitRequest\x1a\x1d.multipaxosrpc.CommitResponse\"\x00B8Z6github.com/psu-csl/replicated-store/go/multipaxos/commb\x06proto3"

var (
	file_multipaxosrpc_proto_rawDescOnce sync.Once
	file_multipaxosrpc_proto_rawDescData []byte
)

func file_multipaxosrpc_proto_rawDescGZIP() []byte {
	file_multipaxosrpc_proto_rawDescOnce.Do(func() {
		file_multipaxosrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_multipaxosrpc_proto_rawDesc), len(file_multipaxosrpc_proto_rawDesc)))
	})
	return file_multipaxosrpc_proto_rawDescData
}

var file_multipaxosrpc_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_multipaxosrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_multipaxosrpc_proto_goTypes = []any{
	(ResponseType)(0),       // 0: multipaxosrpc.ResponseType
	(CommandType)(0),        // 1: multipaxosrpc.CommandType
	(InstanceState)(0),      // 2: multipaxosrpc.InstanceState
	(*AcceptRequest)(nil),   // 3: multipaxosrpc.AcceptRequest
	(*AcceptResponse)(nil),  // 4: multipaxosrpc.AcceptResponse
	(*PrepareRequest)(nil),  // 5: multipaxosrpc.PrepareRequest
	(*PrepareResponse)(nil), // 6: multipaxosrpc.PrepareResponse
	(*CommitRequest)(nil),   // 7: multipaxosrpc.CommitRequest
	(*CommitResponse)(nil),  // 8: multipaxosrpc.CommitResponse
	(*Command)(nil),         // 9: multipaxosrpc.Command
	(*Instance)(nil),        // 10: multipaxosrpc.Instance
}
var file_multipaxosrpc_proto_depIdxs = []int32{
	10, // 0: multipaxosrpc.AcceptRequest.instance:type_name -> multipaxosrpc.Instance
	0,  // 1: multipaxosrpc.AcceptResponse.type:type_name -> multipaxosrpc.ResponseType
	0,  // 2: multipaxosrpc.PrepareResponse.type:type_name -> multipaxosrpc.ResponseType
	10, // 3: multipaxosrpc.PrepareResponse.logs:type_name -> multipaxosrpc.Instance
	0,  // 4: multipaxosrpc.CommitResponse.type:type_name -> multipaxosrpc.ResponseType
	1,  // 5: multipaxosrpc.Command.type:type_name -> multipaxosrpc.CommandType
	2,  // 6: multipaxosrpc.Instance.state:type_name -> multipaxosrpc.InstanceState
	9,  // 7: multipaxosrpc.Instance.command:type_name -> multipaxosrpc.Command
	3,  // 8: multipaxosrpc.MultiPaxosRPC.Accept:input_type -> multipaxosrpc.AcceptRequest
	5,  // 9: multipaxosrpc.MultiPaxosRPC.Prepare:input_type -> multipaxosrpc.PrepareRequest
	7,  // 10: multipaxosrpc.MultiPaxosRPC.Commit:input_type -> multipaxosrpc.CommitRequest
	4,  // 11: multipaxosrpc.MultiPaxosRPC.Accept:output_type -> multipaxosrpc.AcceptResponse
	6,  // 12: multipaxosrpc.MultiPaxosRPC.Prepare:output_type -> multipaxosrpc.PrepareResponse
	8,  // 13: multipaxosrpc.MultiPaxosRPC.Commit:output_type -> multipaxosrpc.CommitResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_multipaxosrpc_proto_init() }
func file_multipaxosrpc_proto_init() {
	if File_multipaxosrpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multipaxosrpc_proto_rawDesc), len(file_multipaxosrpc_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_multipaxosrpc_proto_goTypes,
		DependencyIndexes: file_multipaxosrpc_proto_depIdxs,
		EnumInfos:         file_multipaxosrpc_proto_enumTypes,
		MessageInfos:      file_multipaxosrpc_proto_msgTypes,
	}.Build()
	File_multipaxosrpc_proto = out.File
	file_multipaxosrpc_proto_goTypes = nil
	file_multipaxosrpc_proto_depIdxs = nil
}
